### ISSUE TITLE
Changing a package name

### ISSUE THREAD

**Issue by daroloson** [autopkg/rtrouton-recipes#77]
Don't know how much of a standard it is but I can't see how to change this line
`               <string>%RECIPE_CACHE_DIR%/%VENDOR%_%SOFTWARETITLE%_%version%.pkg</string>`
locally to have -%version% instead of the underscore for MicrosoftSkypeForBusiness365.

**Comment by rtrouton** [comment]
The use of `-` isn’t a standard, but it is a convention that a lot of .pkg recipes use for package naming. In this case, I chose not to do this. The way to change it is to do the following:

1. Make a copy of this recipe, changing the `Indentifier` to something unique and not `com.github.rtrouton.pkg.skypeforbusiness365` and changing `_` to `-`.
2. Host it in your own repository.
3. Have your AutoPkg install use that recipe instead of mine.
